### ISSUE TITLE
segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by itsjjaavii** [vvv-school/tutorial_yarp-ports#2] opened 2024-01-12 19:46 UTC
Hi, yesterday i run the tutorial succesfully, however now i'm trying to run it again and when i have to run $ yarp write /w, the terminal returns "segmentation fault (core dumped)". It happens with both, with tutorial_yarp-ports/port and tutorial_yarp-port/buffered-port. Any ideas on what's happening?
Thanks in advance.

**Comment by pattacini** [comment] 2024-01-15 07:39
Hi @itsjjaavii 

What has changed compared with the previous situation?
Did you install/compile something relevant to the YARP ecosystem?

What type of ecosystem you're using?
- Built from source
- Installed via `conda`
- Docker
- Other...

**Comment by itsjjaavii** [comment] 2024-01-15 12:09
Hello @pattacini,
The only thing that I changed was the main.cpp (i cloned the solution branch), because I wanted to measure the time it takes for the data to be sent, so before the 49 line (outPort.write(output)) I added:

```c++  
auto start_time = std::chrono::high_resolution_clock::now();
```

and after the 49 line I added:

```c++
auto end_time = std::chrono::high_resolution_clock::now();
auto elapsed_time = std::chrono::duration_cast<std::chrono::microseconds>(end_time - start_time);
std::cout << "Time: " << elapsed_time.count() << " microseconds" << std::endl;
```

Plus, I had to include the libraries chrono and iostream. That's everything that i changed. 

The type of ecosystem that I'm using is built from source.

**Comment by pattacini** [comment] 2024-01-15 13:03
When does the `core dumped` occur exactly?
1. When you launch `yarp write /w`?
2. When you text a message into the `yarp write` console to be sent out?

**Comment by itsjjaavii** [comment] 2024-01-15 13:05
I occurs when I launch `yarp write /w`, however I have no issue launching `yarp read /r`.

**Comment by pattacini** [comment] 2024-01-15 13:16
> I occurs when I launch `yarp write /w`, however I have no issue launching `yarp read /r`.

Then, I'd say that this has nothing to do with the tutorial _per se_.
Rather, it pertains to the YARP framework itself.

Perhaps, the YARP network running on your PC is not in a sufficiently "clean" status, meaning there's a hanging process that grabbed the socket associated with the YARP port `/w` and YARP is unaware of that, hence crashing, although it shouldn't.

The crash may depend on how YARP was built? Maybe.

You may try:
1. A cold restart of your system first.
2. Use a different portname for `yarp write`.
3. Investigate with `lsof` who's using that particular socket. See https://ncona.com/2019/03/using-lsof-to-find-who-is-using-a-file-or-socket/.
4. Change the YARP base port, which is usually 10000, to reduce the likelihood of conflicts between YARP and the OS services.

**Comment by itsjjaavii** [comment] 2024-01-16 17:28
Thank you for your response, I will try to do the options you gave me so I can fix this issue

**Comment by pattacini** [comment] 2024-01-30 15:52
Closing as the problem is not related to the tutorial.

**Closed as completed by pattacini** 2024-01-30 15:52 UTC
